# Node Image
FROM node:alpine

# A directory within the virtualized Docker environment
WORKDIR /app

# Copies package.json to Docker environment
COPY package.json /app

# Install all node packages
RUN yarn install --silent

# Copies everything over to Docker environment
COPY . /app

# Runs the application
CMD [ "yarn", "start" ]
